CREATE DATABASE IF NOT EXISTS p6_elit;


DROP TABLE IF  EXISTS guitarwars;
CREATE TABLE IF NOT EXISTS guitarwars(
  id INT AUTO_INCREMENT NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(32),
  score INT,
  screenshot VARCHAR(64),
  PRIMARY KEY (id),
  KEY name (name)
);
