CREATE DATABASE IF NOT EXISTS p6_elit;

CREATE TABLE IF NOT EXISTS guitarwars(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(32),
  score INT
);

DROP TABLE IF  EXISTS guitarwars;
CREATE TABLE IF NOT EXISTS guitarwars(
  id INT AUTO_INCREMENT NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(32),
  score INT,
  PRIMARY KEY (id),
  KEY name (name)
);
